import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from 'react'
import { getTaskWorkspace, getExportState, updateSegment, resegmentTaskWorkspace, restoreTaskPlan, previewVoice, getVoices } from '../api/task'
import { WorkspaceSaveQueue } from './workspaceSaveQueue'
import { readPendingEdits, writePendingEdits } from './workspacePendingStorage'
import { Link } from 'react-router'

export const BatchProjectPreview=forwardRef(function BatchProjectPreview({taskId,onBack,onUpdated},ref){
 const [view,setView]=useState('script'),[segmentIndex,setSegmentIndex]=useState(0)
 const panelRef=useRef(null)
 const [data,setData]=useState(null),[patches,setPatches]=useState({}),[message,setMessage]=useState('加载中…'),[video,setVideo]=useState(''),[audio,setAudio]=useState(''),[voiceName,setVoiceName]=useState(''),[full,setFull]=useState(null),[busy,setBusy]=useState(false)
 const queue=useRef(null),latest=useRef(null),fullRef=useRef(null),bodyKey=`insightcut:batch-fulltext:${taskId}`
 const hasData=Boolean(data)
 useEffect(()=>{if(hasData)panelRef.current?.scrollIntoView?.({behavior:'smooth',block:'start'})},[hasData,taskId])
 useEffect(()=>{let active=true,timer;const q=new WorkspaceSaveQueue({pending:readPendingEdits(taskId),auto:true,send:(i,p)=>updateSegment(taskId,i,p),refresh:()=>getTaskWorkspace(taskId,{silent:true}),onChange:(p,serial,m)=>{if(active){setPatches(p);writePendingEdits(taskId,serial);if(m)setMessage(m)}},onSaved:()=>{onUpdated?.()}});queue.current=q
  try{const saved=JSON.parse(sessionStorage.getItem(bodyKey)||localStorage.getItem(bodyKey)||'null');fullRef.current=saved;setFull(saved)}catch{}
  const load=async()=>{try{const d=await getTaskWorkspace(taskId,{silent:true});if(!active)return;latest.current=d;setData(d);q.rebase(d);const ex=await getExportState(taskId,{silent:true});if(active)setVideo(ex.preview?.valid?ex.preview.manifest?.preview_url||'':'')}catch{if(active)setMessage('加载失败，已有编辑保留，请重试')}finally{if(active)timer=setTimeout(load,2000)}};load();return()=>{active=false;clearTimeout(timer);q.stop()}
 },[taskId])
 useEffect(()=>{let active=true;if(data?.voice_type)getVoices({include_disabled:true}).then(list=>{if(active)setVoiceName(list.find(v=>v.id===data.voice_type)?.name||data.voice_type)}).catch(()=>{if(active)setVoiceName(data.voice_type)});return()=>{active=false}},[data?.voice_type])
 const persistFull=v=>{fullRef.current=v;setFull(v);if(v){const raw=JSON.stringify(v);sessionStorage.setItem(bodyKey,raw);localStorage.setItem(bodyKey,raw)}else{sessionStorage.removeItem(bodyKey);localStorage.removeItem(bodyKey)}}
 useImperativeHandle(ref,()=>({flush:async()=>{if(fullRef.current)throw Error('全文修改尚未保存，请先保存全文并重新拆分');await queue.current.flush();const d=await getTaskWorkspace(taskId,{silent:true});return {task_id:taskId,snapshot_key:d.snapshot_key,plan_version:d.plan_version}}}),[taskId])
 const saveFull=async()=>{setBusy(true);try{await queue.current.flush();const d=await getTaskWorkspace(taskId,{silent:true});if(full.base!==d.script_text)throw Error('全文已被其他页面修改，本地文本已保留；请先比较最新全文');await resegmentTaskWorkspace(taskId,{script_text:full.text,expected_plan_version:d.plan_version});persistFull(null);setMessage('已保存全文，正在重新拆分');onUpdated?.()}catch(e){setMessage(e.response?.data?.detail||e.message)}finally{setBusy(false)}}
 const listen=async()=>{try{const r=await previewVoice({voice_type:data.voice_type,tts_options:data.tts_options});setAudio(r.audio_url||r.preview_url||r.url||'')}catch{setMessage('音色试听失败，请检查配置')}}
 if(!data)return <section className="batch-preview"><button onClick={onBack}>返回项目列表</button><p role="status">{message}</p></section>
 const conflicts=queue.current?.conflicts()||[]
 const segments=data.segments||[],current=segments[Math.min(segmentIndex,Math.max(0,segments.length-1))]
 return <section ref={panelRef} className="batch-preview" aria-label="项目预览">
 <header className="batch-preview-header"><div><span className="batch-preview-eyebrow">预案预览</span><h2>{data.name}</h2><p>{data.ratio} · {segments.length} 个分镜 · {voiceName||'读取音色中'}</p></div><button className="batch-preview-back" onClick={onBack}>关闭预览</button></header>
 <nav className="batch-preview-tabs" aria-label="预览内容">{[['script','文稿'],['storyboard','分镜'],['video','成片'],['edit','编辑预案']].map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}</nav>
 <div className="batch-preview-body">
 {view==='script'&&<div className="batch-preview-manuscript"><p className="batch-preview-eyebrow">完整文稿 · {(full?.text??data.script_text??'').length} 字</p><p>{full?.text??data.script_text??'文稿正在生成，请稍候。'}</p></div>}
 {view==='storyboard'&&(current?<div className="batch-storyboard-card"><div className="batch-storyboard-visual">{current.image_url?<img src={current.image_url} alt={`分镜 ${current.segment_index+1} 画面`}/>:<div><span>{String(current.segment_index+1).padStart(2,'0')}</span><p>画面待生成</p></div>}</div><p className="batch-storyboard-text">{patches[current.segment_index]?.text??current.text}</p><details><summary>查看画面提示词</summary><p>{patches[current.segment_index]?.image_prompt??current.image_prompt}</p></details>{current.audio_url&&<audio controls preload="none" src={current.audio_url}/>}<div className="batch-storyboard-controls"><button disabled={segmentIndex===0} onClick={()=>setSegmentIndex(i=>i-1)}>上一镜</button><span>{Math.min(segmentIndex+1,segments.length)} / {segments.length}</span><button disabled={segmentIndex>=segments.length-1} onClick={()=>setSegmentIndex(i=>i+1)}>下一镜</button></div></div>:<p>分镜正在准备中。</p>)}
 {view==='video'&&(video?<><video className="batch-video" controls preload="metadata" src={video} aria-label="完整成片预览"/><a className="button button-secondary" href={video} download>下载 MP4 视频</a></>:<div className="batch-preview-placeholder"><h3>确认生产后，在这里查看成片</h3><p>当前可以先阅读文稿或逐镜预览方案。</p></div>)}
 {view==='edit'&&<><p role="status">{message}</p><p>{data.text_style} · {data.visual_style} · {data.ratio} · {data.segments_count} 个分镜</p><button onClick={listen}>试听本项目音色</button>{audio&&<audio controls src={audio}/>}
 {video&&<><video className="batch-video" controls preload="metadata" src={video} aria-label="完整成片预览"/><a className="button button-secondary" href={video} download>下载 MP4 视频</a></>}
 <details><summary>本项目实际参数 · {voiceName}</summary><dl><dt>配音音色</dt><dd>{voiceName}</dd><dt>语速</dt><dd>{({very_slow:'很慢',slow:'偏慢',normal:'正常',fast:'偏快',very_fast:'很快'})[data.tts_options?.speed_level]||'正常'}</dd>{data.tts_options?.volume_ratio!=null&&<><dt>音量</dt><dd>{data.tts_options.volume_ratio}</dd></>}{data.tts_options?.style_prompt&&<><dt>声音风格</dt><dd>{data.tts_options.style_prompt}</dd></>}<dt>字幕</dt><dd>{({small:'小',standard:'标准',large:'大'})[data.subtitle_options?.size]}字号 · {({low:'偏低',standard:'标准',high:'偏高'})[data.subtitle_options?.position]}位置</dd><dt>生成策略</dt><dd>提示词并发 {data.generation_options?.prompt_concurrency}，生图并发 {data.generation_options?.image_concurrency}，失败重试 {data.generation_options?.retry_count} 次</dd></dl></details>
 <details open><summary>完整文稿</summary><label className="field"><span>完整文稿正文</span><textarea rows={8} value={full?.text??data.script_text??''} onChange={e=>persistFull({text:e.target.value,base:full?.base??data.script_text})}/></label>{full&&<><button disabled={busy} onClick={saveFull}>保存全文并重新拆分</button><button onClick={()=>persistFull(null)}>采用最新全文</button>{full.base!==data.script_text&&<><p role="alert">全文存在冲突。最新全文：</p><pre>{data.script_text}</pre><button onClick={()=>persistFull({...full,base:data.script_text})}>以本地全文为准，再保存</button></>}</>}{data.can_restore_plan&&<button disabled={busy} onClick={async()=>{setBusy(true);try{if(fullRef.current)throw Error('请先处理全文修改');await queue.current.flush();await restoreTaskPlan(taskId, { expected_plan_version: latest.current.plan_version });onUpdated?.()}catch(e){setMessage(e.message||'恢复失败')}finally{setBusy(false)}}}>恢复上次拆分前版本</button>}</details>
 {conflicts.map(c=><div role="alert" key={`${c.index}:${c.field}`}><p>分镜 {Number(c.index)+1} {c.field==='text'?'文字':'提示词'}存在冲突</p><p>服务器：{c.server}</p><p>本地：{c.value}</p><button onClick={()=>queue.current.resolve(c.index,c.field,true)}>保留本地</button><button onClick={()=>queue.current.resolve(c.index,c.field,false)}>采用服务器</button></div>)}
 <button onClick={()=>queue.current.flush().catch(e=>setMessage(e.message))}>重试保存</button>
 {data.segments.map(s=><article className="batch-preview-segment" key={s.segment_index}><h3>分镜 {s.segment_index+1}</h3>{s.image_url?<img src={s.image_url} alt={`分镜 ${s.segment_index+1} 画面`} loading="lazy"/>:<p>画面方案 · 图片尚未生成</p>}<label className="field"><span>分镜 {s.segment_index+1} 文稿</span><textarea value={patches[s.segment_index]?.text??s.text??''} onChange={e=>queue.current.edit(s.segment_index,{text:e.target.value})}/></label><label className="field"><span>分镜 {s.segment_index+1} 提示词</span><textarea value={patches[s.segment_index]?.image_prompt??s.image_prompt??''} onChange={e=>queue.current.edit(s.segment_index,{image_prompt:e.target.value})}/></label>{s.audio_url&&<audio controls preload="none" src={s.audio_url}/>}</article>)}
 </>}
 </div><footer className="batch-preview-footer"><span>{full||conflicts.length?'有待处理的编辑':'完整编辑与素材管理'}</span><Link to={`/workspace/${taskId}`}>查看项目详情 →</Link></footer>
 </section>
})
