import { useEffect, useRef, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router'
import { createBatch, createProductionTemplate, extractDocumentText, listProductionTemplates } from '../api/task'
import { PlanPresetFields, defaultPreset, templatePreset } from '../components/PlanPresetFields'
import { Modal } from '../components/Modal'
import { batchDraftKey, validateBatch, mapWithConcurrency } from './batchDraft'
import './batch-pages.css'
const card=()=>({id:crypto.randomUUID(),name:'',content:''})
function initial(){try{const d=JSON.parse(localStorage.getItem(batchDraftKey));if(d?.version===2)return d}catch{}return {version:2,mode:'theme',topics:'',cards:[card(),card()],presets:{theme:structuredClone(defaultPreset),script:structuredClone(defaultPreset)},concurrency:3,initialized:false}}
export function BatchComposer({onModeChange}) {
 const [draft,setDraft]=useState(initial),[templates,setTemplates]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[imports,setImports]=useState([]),[saveName,setSaveName]=useState(null)
 const [params]=useSearchParams(),navigate=useNavigate(),ref=useRef(draft),fileInput=useRef(null)
 const patch=p=>setDraft(d=>{const next={...d,...p};ref.current=next;try{localStorage.setItem(batchDraftKey,JSON.stringify(next))}catch{setError('本地存储已满，请保留输入后重试')}return next})
 useEffect(()=>{let live=true;listProductionTemplates().then(r=>{if(!live)return;setTemplates(r.items||[]);const requested=params.get('template');const t=(r.items||[]).find(t=>requested?t.template_id===requested:t.is_default);if(!ref.current.initialized||(requested&&ref.current.appliedLink!==requested)){const presets={...ref.current.presets};if(t){if(!ref.current.initialized){presets.theme=templatePreset(t);presets.script=templatePreset(t)}else presets[ref.current.mode]=templatePreset(t);}patch({presets,initialized:true,appliedLink:requested})}}).catch(()=>setError('预案模板读取失败，可使用当前设置'));return()=>{live=false}},[params])
 const preset=draft.presets[draft.mode], validation=validateBatch(draft.mode,draft.topics,draft.cards)
 const changePreset=v=>patch({presets:{...ref.current.presets,[ref.current.mode]:v}})
 const updateCard=(id,p)=>patch({cards:ref.current.cards.map(c=>c.id===id?{...c,...p}:c)})
 const importFiles=async files=>{setBusy(true);const selected=Array.from(files);fileInput.current.value='';const slots=50-ref.current.cards.filter(c=>c.name.trim()||c.content.trim()).length;if(selected.length>slots){setError(`最多还能导入 ${slots} 篇，请先移除不需要的卡片`);setBusy(false);return}const entries=selected.map(f=>({id:crypto.randomUUID(),name:f.name,status:'等待提取'}));setImports(entries);const imported=[];await mapWithConcurrency(selected,2,async(f,i)=>{try{if(f.size>20*1024*1024)throw Error('文件超过 20 MiB');const r=await extractDocumentText(f);imported[i]={id:entries[i].id,name:f.name.replace(/\.[^.]+$/,''),content:r.text};setImports(a=>a.map(x=>x.id===entries[i].id?{...x,status:'已导入'}:x))}catch(e){setImports(a=>a.map(x=>x.id===entries[i].id?{...x,status:e.response?.data?.detail||e.message||'提取失败'}:x))}});if(imported.some(Boolean))patch({cards:[...ref.current.cards.filter(c=>c.name.trim()||c.content.trim()),...imported.filter(Boolean)]});setBusy(false)}
 const submit=async()=>{setError('');if(validation.errors.length)return;setBusy(true);try{const result=await createBatch({items:validation.items,input_mode:draft.mode,concurrency:draft.concurrency,...preset,style:`${preset.text_style}|${preset.visual_style}`,length:draft.mode==='theme'?preset.length:0,voice_type:preset.voice_type||undefined});navigate(`/batches/${result.batch_id}`)}catch(e){setError(typeof e.response?.data?.detail==='string'?e.response.data.detail:'创建失败，请检查设置后重试')}finally{setBusy(false)}}
 const saveTemplate=async()=>{try{const t=await createProductionTemplate({...preset,name:saveName,is_default:false});setTemplates(a=>[...a,t]);changePreset(templatePreset(t));setSaveName(null)}catch{setError('保存模板失败')}}
 return <main className="creation-page batch-composer-page">
  <nav aria-label="项目创建模式"><button onClick={()=>onModeChange('single')}>单项目</button><button aria-current="page">批量预案</button></nav>
  <div className="batch-compose-grid"><section className="writing-canvas"><h1>批量预案</h1><p>一次创建 2–50 个项目，预案完成后可直接全选确认生产，也可先预览。</p>
   <div className="segmented-control">{[['theme','主题模式'],['script','完整文稿模式']].map(([m,n])=><button key={m} aria-pressed={draft.mode===m} onClick={()=>patch({mode:m})}>{n}</button>)}</div>
   {draft.mode==='theme'?<><label className="field"><span>主题清单，每行一个</span><textarea rows={12} aria-label="批量主题，每行一个" value={draft.topics} onChange={e=>patch({topics:e.target.value})} placeholder={'为什么海水是咸的\n人为什么会做梦'}/></label><ol>{validation.items.map((i,n)=><li key={n}>{i.content} <small>{i.content.length}/100 字</small></li>)}</ol></>:<><p>一张卡片是一篇完整文稿。正文中的换行、空行不会创建新项目。</p>{draft.cards.map((c,n)=><article className="batch-script-card" key={c.id}><h3>文稿 {n+1}</h3><label className="field"><span>项目名称 {n+1}</span><input maxLength={100} value={c.name} onChange={e=>updateCard(c.id,{name:e.target.value})}/></label><label className="field"><span>完整正文 {n+1}</span><textarea rows={7} value={c.content} onChange={e=>updateCard(c.id,{content:e.target.value})}/></label><small>{c.content.length}/5000 字</small><div><button disabled={busy||draft.cards.length>=50} onClick={()=>patch({cards:[...draft.cards,{...c,id:crypto.randomUUID()}]})}>复制文稿 {n+1}</button><button disabled={busy} onClick={()=>patch({cards:draft.cards.filter(x=>x.id!==c.id)})}>删除文稿 {n+1}</button></div></article>)}<button disabled={busy||draft.cards.length>=50} onClick={()=>patch({cards:[...draft.cards,card()]})}>新增文稿</button><button disabled={busy} onClick={()=>fileInput.current.click()}>导入多个文档</button><input ref={fileInput} type="file" hidden multiple accept=".txt,.md,.markdown,.docx,.pdf" onChange={e=>importFiles(e.target.files)}/><ul aria-live="polite">{imports.map(x=><li key={x.id}>{x.name}：{x.status}</li>)}</ul></>}
   <p>{validation.items.length}/50 个项目</p>{validation.errors.map(e=><p role="alert" key={e}>{e}</p>)}
  </section><aside className="work-panel batch-preset"><h2>本批设置</h2><p>模板供单项目和批量共用；此处修改仅用于本批次。</p><label className="field"><span>预案模板</span><select value={preset.template_id||''} onChange={e=>{const t=templates.find(t=>t.template_id===e.target.value);changePreset(t?templatePreset(t):structuredClone(defaultPreset))}}><option value="">产品默认设置</option>{templates.map(t=><option key={t.template_id} value={t.template_id}>{t.name}</option>)}</select></label><p>{preset.template_name||'产品默认设置'}{preset.adjusted?' · 已调整':''}</p>
   <PlanPresetFields value={preset} onChange={changePreset} theme={draft.mode==='theme'} disabled={busy}/><button onClick={()=>setSaveName('我的预案模板')}>保存为预案模板</button>
   <label className="field"><span>同时运行项目数</span><input type="number" min="1" max="10" value={draft.concurrency} onChange={e=>patch({concurrency:Math.max(1,Math.min(10,Number(e.target.value)||1))})}/></label><p>一批最多 50 个；本批同时运行 {draft.concurrency} 个，其余自动排队。全系统生成上限 10 个，MP4 同时渲染 1 个。</p>
   {error&&<p role="alert">{error}</p>}<button className="button button-primary" disabled={busy||validation.errors.length>0} onClick={submit}>{busy?'正在处理…':`创建 ${validation.items.length} 个预案`}</button><button onClick={()=>navigate('/batches')}>查看已有批次</button>
  </aside></div>
  <Modal open={saveName!==null} title="保存为新的预案模板" onClose={()=>setSaveName(null)} footer={<button disabled={!saveName?.trim()} onClick={saveTemplate}>保存模板</button>}><label>模板名称<input value={saveName||''} onChange={e=>setSaveName(e.target.value)}/></label></Modal>
 </main>
}
